### ADMIN APIS

### Members
GET http://localhost:3000/api/admin/members/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IndyaXRlcm5pa2hpbGVzaEBnbWFpbC5jb20iLCJyb2xlIjoibWVtYmVyIiwiaWF0IjoxNzUzMjcxNjg4fQ._HvK6uCsmOvWRaV5F_zPHKVutE4_zW3RUPiT4PsMe_E

###
GET http://localhost:3000/api/admin/members/raju1234@gmail.com/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVubWlkZnVsYXRvbm9teTlAZ21haWwuY29tIiwiaWF0IjoxNzUxMDM3OTM3fQ.H2X83-_NEzCgPHxL5kvTSMxkHKrw7LeqjMUrsLztGPg

###
POST http://localhost:3000/api/admin/members/
Content-Type: application/json

{
    "name" :"Nikhilesh",
    "email":"witernikhilesh@gmail.com",
    "phone": "6305194242",
    "gender": "Male",
    "age": 18,
    "joinDate":"2025-06-18",
    "packageId":1,
    "active":true    
}
###
PUT http://localhost:3000/api/admin/members/1/
Content-Type: application/json

{
    "name" :"Nikhilesh",
    "email":"witernikhilesh@gmail.com",
    "phone": "6305194243",
    "gender": "Male",
    "age": 18,
    "joinDate":"2025-06-18",
    "packageId":1,
    "active":true     
}

###

DELETE http://localhost:3000/api/admin/members/raju1234@gmail.com/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVubWlkZnVsYXRvbm9teTlAZ21haWwuY29tIiwiaWF0IjoxNzUxMDM3OTM3fQ.H2X83-_NEzCgPHxL5kvTSMxkHKrw7LeqjMUrsLztGPg

### Bills

POST http://localhost:3000/api/admin/bills/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IndyaXRlcm5pa2hpbGVzaEBnbWFpbC5jb20iLCJyb2xlIjoibWVtYmVyIiwiaWF0IjoxNzUzMjcxNjg4fQ._HvK6uCsmOvWRaV5F_zPHKVutE4_zW3RUPiT4PsMe_E
Content-Type: application/json

{
    "memberId":2,
    "amountPaid":2000,
    "method":"Cash"    
}
###
GET http://localhost:3000/api/admin/bills/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IndyaXRlcm5pa2hpbGVzaEBnbWFpbC5jb20iLCJyb2xlIjoibWVtYmVyIiwiaWF0IjoxNzUzMjcxNjg4fQ._HvK6uCsmOvWRaV5F_zPHKVutE4_zW3RUPiT4PsMe_E

###
GET http://localhost:3000/api/admin/bills/member/1/

###
GET http://localhost:3000/api/admin/bills/1/

### Fee Packages

POST http://localhost:3000/api/admin/packages/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVubWlkZnVsYXRvbm9teTlAZ21haWwuY29tIiwiaWF0IjoxNzUxMDM3OTM3fQ.H2X83-_NEzCgPHxL5kvTSMxkHKrw7LeqjMUrsLztGPg
Content-Type: application/json

{
    "name":"monthly",
    "durationDays": 30,
    "amount": 1500,
    "description": "1 month access to the gym." 
}
###

GET http://localhost:3000/api/admin/packages/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVubWlkZnVsYXRvbm9teTlAZ21haWwuY29tIiwiaWF0IjoxNzUxMDM3OTM3fQ.H2X83-_NEzCgPHxL5kvTSMxkHKrw7LeqjMUrsLztGPg
###
GET http://localhost:3000/api/admin/packages/1/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVubWlkZnVsYXRvbm9teTlAZ21haWwuY29tIiwiaWF0IjoxNzUxMDM3OTM3fQ.H2X83-_NEzCgPHxL5kvTSMxkHKrw7LeqjMUrsLztGPg

###
PUT  http://localhost:3000/api/admin/packages/1/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVubWlkZnVsYXRvbm9teTlAZ21haWwuY29tIiwiaWF0IjoxNzUxMDM3OTM3fQ.H2X83-_NEzCgPHxL5kvTSMxkHKrw7LeqjMUrsLztGPg
Content-Type: application/json

{
    "name":"2-Year",
    "durationDays": 730,
    "amount": 35000,
    "description": "24-month VIP access + 24 personal trainings + free locker." 
}
###
DELETE http://localhost:3000/api/admin/packages/1/

### Notifications

POST http://localhost:3000/api/admin/notifications/
Content-Type: application/json

{
    "title":"Reminder for this month fee payment for monthly students",
    "message":"All the members that haven't payed the fee this month are requested to pay by tomorrow.",
    "targetType":"member"
}

### 
GET http://localhost:3000/api/admin/notifications/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVubWlkZnVsYXRvbm9teTlAZ21haWwuY29tIiwiaWF0IjoxNzUxMDM3OTM3fQ.H2X83-_NEzCgPHxL5kvTSMxkHKrw7LeqjMUrsLztGPg
###
GET http://localhost:3000/api/admin/notifications/1/
###
DELETE http://localhost:3000/api/admin/notifications/1/


### Suppliments
POST http://localhost:3000/api/admin/supplements/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVubWlkZnVsYXRvbm9teTlAZ21haWwuY29tIiwiaWF0IjoxNzUxMDM3OTM3fQ.H2X83-_NEzCgPHxL5kvTSMxkHKrw7LeqjMUrsLztGPg
Content-Type: application/json

{
    "name": "Multivitamin",
    "price": 499.00,
    "description": "Daily essential vitamins and minerals for overall wellness.",
    "stockQuantity": 100,
    "url": "https://i.ibb.co/4ndHkjKw/image.png"
}

###
GET  http://localhost:3000/api/admin/supplements/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVubWlkZnVsYXRvbm9teTlAZ21haWwuY29tIiwiaWF0IjoxNzUxMDM3OTM3fQ.H2X83-_NEzCgPHxL5kvTSMxkHKrw7LeqjMUrsLztGPg

###
GET  http://localhost:3000/api/admin/supplements/1/

###
PUT  http://localhost:3000/api/admin/supplements/1/
Content-Type: application/json

{
    "name": "Whey Protein",
    "price":1800,
    "description":"High-quality protein for muscle recovery and growth.",
    "stockQuantity":30
}
###
DELETE http://localhost:3000/api/admin/supplements/1/

### admin login
POST  http://localhost:3000/api/login/
Content-Type: application/json

{
    "email":"unmidfulatonomy9@gmail.com",
    "password":"Nikhilesh@2005",
    "role":"admin"
}

### reset password api
PUT http://localhost:3000/api/reset-password/
Content-Type: application/json

{
    "email":"writernikhilesh@gmail.com",
    "password":"Nikhilesh@2005",
    "role":"member"
}

### 